# -*- coding: utf-8 -*-
"""Encode and Decode TinyURL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mnoaXf6z152VeFxMMX7vRANf1umuZ0QU
"""

class Codec:
    def __init__(self):
        self.my_dict={}
        self.st=0
        self.b="http//tinyurl/"

    def encode(self, longUrl: str) -> str:
        """Encodes a URL to a shortened URL.
        """
        res=self.b+str(self.st)
        self.st+=1
        self.my_dict[res]=longUrl
        return res
        

    def decode(self, shortUrl: str) -> str:
        """Decodes a shortened URL to its original URL.
        """
        return self.my_dict[shortUrl]