# -*- coding: utf-8 -*-
"""Find All Numbers Disappeared in an Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XM2P4tR1RorX8MP9HHZZ-AEUgxVcEaS_
"""

class Solution:
    def findDisappearedNumbers(self, nums: List[int]) -> List[int]:
        for n in nums:
            i=abs(n)-1
            nums[i]=-1*abs(nums[i])
        res=[]
        for i,n  in enumerate(nums):
            if n>0:
                res.append(i+1)
        return res