# -*- coding: utf-8 -*-
"""Find All Anagrams in a String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w2Yc3bKcHjlqEhMMk-Xlfkjyh-4lmcg6
"""

class Solution:
    def findAnagrams(self, s: str, p: str) -> List[int]:
        p_len=len(p)
        s_len=len(s)
        if len(s)<len(p):
            return []
        vp=[0] * 26
        vs=[0] * 26
        res=[]    
        for i in range(p_len):
            vp[ord(p[i])-97]+=1
        start=0
        for i in range(s_len):
        
            vs[ord(s[i])-97]+=1
            if i>=p_len:
                vs[ord(s[start])-97]-=1
                start+=1
            if vp==vs:
                res.append(start) 
        return res