# -*- coding: utf-8 -*-
"""Largest Number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Rrq0PnC38v52tlB1hF2D2uARE5jhbQL
"""

class Solution:
    def largestNumber(self, nums: List[int]) -> str:
        
        for i,n  in enumerate (nums):
            nums[i]=str(n)
        def compare(n1,n2):
            if n1+n2>n2+n1 :
                return -1 
            else:
                return 1          
        nums=sorted(nums,key=cmp_to_key(compare)) 
        return str(int("".join(nums)))