# -*- coding: utf-8 -*-
"""Minimum Number of Swaps to Make the String Balanced.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B19OiDLhI6YPIMZNCFId3Ae8zY-Es7UA
"""

class Solution:
    def minSwaps(self, s: str) -> int:
        exstra_close=0
        mx=0
        for i in range(len(s)):
            if s[i]==']':
                exstra_close+=1
            else:
                exstra_close-=1
            mx=max(mx,exstra_close)
        return( (mx+1 )//2 )