# -*- coding: utf-8 -*-
"""Repeated DNA Sequences.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bm8B2140R9sli5K2jWzItbP3MzC0GQUZ
"""

class Solution:
    def findRepeatedDnaSequences(self, s: str) -> List[str]:
        my_dict={}
        res=set()
        tmp="" 
        for i in range(len(s)):
            tmp+=s[i]
            if len(tmp)==10:
                if tmp in my_dict.keys():
                    my_dict[tmp]+=1
                    res.add(tmp)
                else:
                    my_dict[tmp]=1 
                tmp=tmp[1:]
        return res