# -*- coding: utf-8 -*-
"""Word Pattern.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19rRImW3n5HS3woY6_UMzwUVk80aOqlg7
"""

class Solution:
    def wordPattern(self, pattern: str, s: str) -> bool:
        words=s.split(" ")
        if len(pattern)!= len(words):
            return False
        d1={}
        d2={}    
        for c,w in zip(pattern,words)  :
            if c in d1 and d1[c]!=w:
                return False
            if w in d2 and d2[w]!=c:
                return False
            d1[c]=w
            d2[w]=c
        return True