# -*- coding: utf-8 -*-
"""Container With Most Water.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JsiuW3DwAcoUYzhQ1Q-z3ofAifQCkcH7
"""

class Solution:
    def maxArea(self, height: List[int]) -> int:
        L=0
        R=len(height)-1
        mx=0
        while L<R:
            res=min(height[L],height[R])*(R-L)
            mx=max(mx,res)
            if height[L]<height[R]:
                L+=1
            else:
                R-=1
        return mx