# -*- coding: utf-8 -*-
"""Minimum Difference Between Highest and Lowest of K.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NCaES-TyZ9gWmVMpeLQA1j28ZhCAAy-a
"""

class Solution:
    def minimumDifference(self, nums: List[int], k: int) -> int:
        nums.sort()
        res=float("inf")
        p1=0
        p2=k-1
        while p2<len(nums):
            res=min(res,nums[p2]-nums[p1])
            p1+=1
            p2+=1
        return res