# -*- coding: utf-8 -*-
"""Move_Zeroes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D26HnT94uUGyJPpY3VHsLNtn9C862eoJ
"""

class Solution:
    def moveZeroes(self, nums: List[int]) -> None:
        """
        Do not return anything, modify nums in-place instead.
        """
        L=0
        for i in range (0,len(nums)):
            if nums[i]!=0:
                nums[L]=nums[i]
                L+=1
               
        for j in range(L,len(nums)):
            nums[j]=0