# -*- coding: utf-8 -*-
"""Number of Subsequences That Satisfy the Given Sum Condition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kiH5q5t_AqGjgk1AyDr_BgCeU9hgJtcJ
"""

class Solution:
    def numSubseq(self, nums: List[int], target: int) -> int:
        nums.sort()
        mod = 10**9 + 7
        left = 0
        right = len(nums) - 1
        res = 0
      
        while(left <= right):
            if nums[left] + nums[right] > target:
                right -= 1
            else:
                num_inside = right - left
                res = (res + pow(2, num_inside, mod)) % mod
                left += 1
        return res