# -*- coding: utf-8 -*-
"""Remove Duplicates from Sorted Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m8QWz7oJsKphuMdmmxPHtgyVIwe5j0bE
"""

class Solution:
    def removeDuplicates(self, nums: List[int]) -> int:
        c=0
        for i in range(0,len(nums)):
            while  i + 1 < len(nums) and nums[i]==nums[i+1] :
                nums.remove(nums[i])
                c+=1
        return len(nums)