# -*- coding: utf-8 -*-
"""Rotate Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b5opeFnDcj-ZdGlolvJPlrtDPGfz7tkS
"""

class Solution:
    def rotate(self, nums: List[int], k: int) -> None:
        """
        Do not return anything, modify nums in-place instead.
        """
        def reverse_sublist(lst,start,end):
            lst[start:end] = lst[start:end][::-1]
            return lst
        if len(nums)==1:
            return 
        k=k % (len(nums) )
        nums.reverse()
        nums=reverse_sublist(nums,0,k)
        nums=reverse_sublist(nums,k,len(nums))