# -*- coding: utf-8 -*-
"""Two Sum_II_Input Array Is Sorted.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PiajqyhNhHNEmyjZvEo7RpMUxox9edCj
"""

class Solution:
    def twoSum(self, numbers: List[int], target: int) -> List[int]:
        L=0
        R=len(numbers)-1
        while(L<=R):
            if numbers[L]+numbers[R]==target:
                return [L+1,R+1]
            if  numbers[L]+numbers[R]>target:
                R-=1
            else:
                L+=1
        return [-1,-1]