# -*- coding: utf-8 -*-
"""Valid Palindrome II.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SdjZ5OHwWvexA6HX20gsocYh1mCt-NSM
"""

class Solution:
    def validPalindrome(self, s: str) -> bool:
        L, R = 0, len(s) - 1
        
        while L < R:
            if s[L] == s[R]:
                L += 1
                R -= 1
            else:
                return self.is_palin(s, L + 1, R) or self.is_palin(s, L, R- 1)
        return True
    
    def is_palin(self, s, i, j):
        while i < j:
            if s[i] == s[j]:
                i += 1
                j -= 1
            else:
                return False